### PR TITLE
Feat/metapopulation

### PR DESCRIPTION
**Pull request by giovannic**
A metapopulation model for spatial modelling.

You can test it with `run_metapop_simulation`. For info, see `?run_metapop_simulation`

CHANGES

Implement metapopulation model
 * e2e, integration and unit tests for metapopulation modelling
 * run_metapop_simulation function for setting up and integrating
   multiple models
 * update calculate_foim for multiple infectivity values
 * remove over-complicated disease progression events
 * Add diagnostic rendering and documentation for net_usage

Review stages:

- [x] does it work as expected? @htopazian 
- [ ] is the code maintainable? TBA

### CODE REVIEW

**Comment by htopazian** [comment]
Hi Giovanni, I really like the function set-up and the way you've structured everything. 

I'm doing some tests -- even with no seasonality and isolated mixing (1s on the diagonal), it seems like the patches are still influencing eachother somehow? I'm just showing here the runs for run_metapop_simulation

[test.pdf](https://github.com/mrc-ide/malariasimulation/files/8939395/test.pdf)

```library(dplyr)
library(ggplot2)
library(data.table)
library(malariaEquilibrium)
library(malariasimulation)

year <- 365
human_population <- 10000
sim_length <- 10 * year
EIR_vector <- c(1, 2, 5)


# run metapopulation model
ms_mixed <- function(x){
  
  params <- get_parameters(list(human_population = human_population,
                                individual_mosquitoes = FALSE))
  params <- set_drugs(params, list(AL_params))
  params <- set_clinical_treatment(params, drug = 1, timesteps = 1, coverages = 0.40)

  params <- set_equilibrium(params, init_EIR = EIR_vector[x])
  
}

paramslist <- lapply(seq(1, length(EIR_vector), 1), ms_mixed)

output <- run_metapop_simulation(timesteps = sim_length,
                                 parameters = paramslist,
                                 correlations = NULL,
                                 mixing = diag(length(EIR_vector)))

model3 <- data.table::rbindlist(output, idcol = 'EIR') %>%
  mutate(EIR = c(sort(rep(EIR_vector, sim_length)))) %>%
  mutate(prev2to10 = p_detect_730_3650 / n_730_3650) %>%
  mutate(month = ceiling(timestep/(year/12))) %>%
  group_by(EIR, month) %>%
  mutate(prev2to10 = mean(prev2to10, na.rm = T))

ggplot(data = model3) +
  # geom_vline(data = segments, aes(xintercept = years_dist), color = 'lightgrey', lty = 2) +
  geom_line(aes(x = month / 12, y = prev2to10)) +
  scale_y_continuous(limits = c(0, 0.4)) +
  facet_wrap(~ EIR, labeller = label_both) +
  labs(x = 'time (years)',
       y = 'PfPR 2-10 (month)',
       title = 'run_simulation vs. run_metapop_simulation',
       color = '',
       caption = paste0('population = ', human_population)) +
  theme_classic()

**Comment by giovannic** [comment]
Thanks @htopazian I think your case should work now

**Comment by giovannic** [comment]
Thanks @htopazian, the events were broken!

All of the events for the three populations were  set up for the last population. I used a `for` loop to set up events for each population, but R is "Lazy" so it waited until the for loop to reach the last population before setting up the events. We now use `forceAndCall` to make sure R sets up each event during the `for` loop.

I also added a net_usage output to the model, showing the number of people with nets. Since that's what led me to the solution!

**Comment by htopazian** [comment]
Thanks @giovannic, 

Great idea to add the net_usage output - I've been calculating this by multiplying population * net usage, but this will be a good output to have when we start adding in correlations and it becomes harder to calculate. And so we can visualize decays in ITN use!

The script is running beautifully now, let me do a few more tests with seasonality and adding the mixing, but it is looking really good. 
 
image

**Comment by htopazian** [comment]
ITN decay looking v crisp :)

image

Mixing not so much for patterns other than the identity matrix. We should see the perfectly mixed EIR lines all converging. 
We should also put in an error message for scenarios where the rows and columns of the mixing matrix don't add up to one.

image

Some more test code, perhaps check to make sure I am parameterizing the mixing matrix correctly? 

```
# testing malariasimulation, metapopulation function

# load libraries
library(dplyr)
library(ggplot2)
library(purrr)
library(data.table)
library(malariaEquilibrium)
library(malariasimulation)
# devtools::install_github('https://github.com/mrc-ide/malariasimulation/tree/feat/metapopulation', force = T)

# set variables
year <- 365
human_population <- 2000
sim_length <- 30 * year
EIR_vector <- c(1, 2, 5)


# get parameters
ms_parameterize <- function(x){ # index of EIR and ITN vector
  
  params <- get_parameters(list(human_population = human_population,
                                model_seasonality = FALSE,
                                individual_mosquitoes = FALSE))
  params <- set_drugs(params, list(AL_params))
  params <- set_clinical_treatment(params, drug = 1, timesteps = 1, coverages = 0.40)

  params <- set_equilibrium(params, init_EIR = EIR_vector[x])
  
  print(paste0('Set params: ', x))
  
  return(params)
  
}

paramslist <- lapply(seq(1, length(EIR_vector), 1), ms_parameterize)


# run model
set.seed(123)

# isolated
output <- run_metapop_simulation(timesteps = sim_length,
                                 parameters = paramslist,
                                 correlations = NULL,
                                 mixing = diag(length(EIR_vector)))

isolate <- data.table::rbindlist(output, idcol = 'EIR') %>%
  mutate(EIR = c(sort(rep(EIR_vector, sim_length))))

# perfectly mixed
output <- run_metapop_simulation(timesteps = sim_length,
                                 parameters = paramslist,
                                 correlations = NULL,
                                 mixing = matrix(rep(.33, 9),
                                                 nrow = 3, ncol = 3))

mixed <- data.table::rbindlist(output, idcol = 'EIR') %>%
  mutate(EIR = c(sort(rep(EIR_vector, sim_length))))

# slightly mixed
output <- run_metapop_simulation(timesteps = sim_length,
                                 parameters = paramslist,
                                 correlations = NULL,
                                 mixing = matrix(c(0.8, 0.1, 0.1, 
                                                   0.1, 0.8, 0.1,
                                                   0.1, 0.1, 0.1),
                                                 nrow = 3, ncol = 3))

middle <- data.table::rbindlist(output, idcol = 'EIR') %>%
  mutate(EIR = c(sort(rep(EIR_vector, sim_length))))


# merge dataframes
mdat <- isolate %>% mutate(model = 'isolated') %>%
  full_join(mixed %>% mutate(model = 'perfectly mixed')) %>%
  full_join(middle %>% mutate(model = 'lightly mixed')) %>%
  mutate(prev2to10 = p_detect_730_3650 / n_730_3650) %>%
  mutate(year = ceiling(timestep/year)) %>%
  group_by(model, EIR, year) %>%
  mutate(prev2to10 = mean(prev2to10, na.rm = T))

ggplot(data = mdat) + 
  geom_line(aes(x = year, y = prev2to10, color = factor(EIR))) +
  facet_wrap(~ model) +
  labs(x = 'time (years)',
       y = 'PfPR 2-10 (month)',
       title = 'Mixing patterns, no ITNs',
       color = 'EIR') +
  theme_classic()

ggsave('C:/Users/htopazia/Desktop/test_mixing.pdf', height = 4, width = 6)
```

**Comment by htopazian** [comment]
beautiful! re-ran all tests above and all are checking out

image

**Review by htopazian — APPROVED** [review]
Hi Giovanni, 

This looks very nice. I've added a couple tests for the mixing matrix rows and columns. And a vignette. Have a look over and see if I described things accurately - good to merge on my end once those changes are finalized!

**Pull request merged**
