### PR TITLE
Add fast weighted sample to biting process

### PR DESCRIPTION
**Pull request by giovannic**
A little optimisation in random number generation:

 * Uses fast RNGs from dqrng
 * Implements weighted sampling using bucket method from https://arxiv.org/pdf/1903.00227.pdf

Performance-wise it's a 2x...

```r
n <- 1e6
m <- n / 2
prob <- rexp(n)
prob <- prob / max(prob)
bench::mark(
  sample.int(n, m, TRUE, prob),
  malariasimulation:::fast_weighted_sample(m, prob),
  check=FALSE
)

# > A tibble: 2 x 13
# > expression                                             min  median `itr/sec` mem_alloc
# > <bch:expr>                                        <bch:tm> <bch:t>     <dbl> <bch:byt>
# > 1 sample.int(n, m, TRUE, prob)                        83.9ms  91.8ms      11.0   13.36MB
# > 2 malariasimulation:::fast_weighted_sample(m, prob)   38.6ms  43.3ms      23.7    3.81MB
# > … with 8 more variables: gc/sec <dbl>, n_itr <int>, n_gc <dbl>, total_time <bch:tm>,
# >  result <list>, memory <list>, time <list>, gc <list>
```

### CODE REVIEW

**Comment by giovannic** [comment]
closing, I've missed an edge case

**Comment by giovannic** [comment]
Fixed a segfault when all weights are the same

**Review by richfitz — CHANGES_REQUESTED** [review]
```
  Running ‘testthat.R’/Library/Frameworks/R.framework/Resources/bin/BATCH: line 60:  6890 Abort trap: 6           ${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1
```

Looks like you still have a segfault here.


```
⠧ |   5 3     | biology                                                                                                                                                   ==49129== Invalid write of size 8
==49129==    at 0x12DCC503: Random::prop_sample_bucket(unsigned long, std::vector<double, std::allocator<double> >) (Random.cpp:90)
==49129==    by 0x12E1F06F: fast_weighted_sample(unsigned long, std::vector<double, std::allocator<double> >) (utils.cpp:27)
==49129==    by 0x12DD3B30: _malariasimulation_fast_weighted_sample (RcppExports.cpp:228)
==49129==    by 0x493FCBB: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4940205: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4995702: Rf_eval (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4998B92: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x49954BA: Rf_eval (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4996E8E: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4997D81: Rf_applyClosure (in /usr/lib/R/lib/libR.so)
==49129==    by 0x49846FD: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4994FC7: Rf_eval (in /usr/lib/R/lib/libR.so)
==49129==  Address 0x8d7e4c0 is 0 bytes after a block of size 800 alloc'd
==49129==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==49129==    by 0x12DCC418: allocate (new_allocator.h:114)
==49129==    by 0x12DCC418: allocate (alloc_traits.h:444)
==49129==    by 0x12DCC418: _M_allocate (stl_vector.h:343)
==49129==    by 0x12DCC418: _M_create_storage (stl_vector.h:358)
==49129==    by 0x12DCC418: _Vector_base (stl_vector.h:302)
==49129==    by 0x12DCC418: vector (stl_vector.h:508)
==49129==    by 0x12DCC418: Random::prop_sample_bucket(unsigned long, std::vector<double, std::allocator<double> >) (Random.cpp:59)
==49129==    by 0x12E1F06F: fast_weighted_sample(unsigned long, std::vector<double, std::allocator<double> >) (utils.cpp:27)
==49129==    by 0x12DD3B30: _malariasimulation_fast_weighted_sample (RcppExports.cpp:228)
==49129==    by 0x493FCBB: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4940205: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4995702: Rf_eval (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4998B92: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x49954BA: Rf_eval (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4996E8E: ??? (in /usr/lib/R/lib/libR.so)
==49129==    by 0x4997D81: Rf_applyClosure (in /usr/lib/R/lib/libR.so)
==49129==    by 0x49846FD: ??? (in /usr/lib/R/lib/libR.so)
==49129== 
```

This is the first result from valgrind (takes a while!) but may be the culprit.

**Comment by giovannic** [comment]
Non-allocating version.

```
# A tibble: 2 x 13
  expression                                             min  median `itr/sec` mem_alloc
  <bch:expr>                                        <bch:tm> <bch:t>     <dbl> <bch:byt>
1 sample.int(n, m, TRUE, prob)                        80.9ms  92.6ms      11.0   13.36MB
2 malariasimulation:::fast_weighted_sample(m, prob)   36.6ms  42.1ms      23.0    7.31MB
# … with 8 more variables: gc/sec <dbl>, n_itr <int>, n_gc <dbl>, total_time <bch:tm>,
#   result <list>, memory <list>, time <list>, gc <list>
```

I'll take it

**Review by richfitz — APPROVED** [review]

**Pull request merged**
