### PR TITLE
Changing create_progression_process() rates to probs

### PR DESCRIPTION
**Pull request by tbreweric**
As raised in the PR #289, the `create_progression_process()` function (`disease_progression.R`), which governs the way individuals move between some pairs of states, has an argument `rate` which is currently passed mean state duration time (e.g. `parameters$dd`. Within the function, the inverse of this `rate` argument is used to sample individuals to move between states.

While a fix has been suggested for naming the `Bitset$sample()` function in the individual package, in the meantime the malariasimulation code has been made clearer by:

-  Changing the name of the `rate` argument to `prob` in the `create_progression_process()` and `create_asymptomatic_progression_process()` functions.
- Changing the inputs to the `create_progression_process()` and `create_asymptomatic_progression_process()` function calls in `create_processes()` from the former average residence time (`parameters$dd`) to the probability `1 - exp(-1/parameters$dd)`

### CODE REVIEW

**Comment by tbreweric** [comment]
I've now fixed (hopefully) the conflicts, so ready for the changes to be reviewed now @giovannic @pwinskill !

**Comment by tbreweric** [comment]
Have seen this is failing the CMD checks - checking to see what the issue(s) is/are

**Comment by tbreweric** [comment]
Have implemented the changes suggested above - seems to have solved the CMD check failures.

**Review by giovannic — CHANGES_REQUESTED** [review]

**Comment by giovannic** [comment]
obsolete

**Pull request closed without merging**
